<a href="https://colab.research.google.com/github/manikant070/manikant/blob/main/python18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
h = [30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [ ]:
import numpy as np

In [ ]:
d=np.array(h)
d

array([30, 20,  5,  8,  9])

In [ ]:
k = d+5
k

array([35, 25, 10, 13, 14])

In [ ]:
s = (6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [ ]:
j=tuple(x**2 for x in s)
j

(36, 4, 9, 81, 49, 25, 64)

In [ ]:
f = []
for b in j:
  if b>30:
    f.append(b)


In [ ]:
f

[36, 81, 49, 64]

In [ ]:
d=np.array([20,50,30,70,80,40,36,54,98])
d

array([20, 50, 30, 70, 80, 40, 36, 54, 98])

In [ ]:
d+5

array([ 25,  55,  35,  75,  85,  45,  41,  59, 103])

In [ ]:
d**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916, 9604])

In [ ]:
d

array([20, 50, 30, 70, 80, 40, 36, 54, 98])

In [ ]:
d[d>30]

array([False,  True, False,  True,  True,  True,  True,  True,  True])

In [31]:
d[d>50]

array([70, 80, 54, 98])

In [32]:
np.where(d>50)

(array([3, 4, 7, 8]),)