<a href="https://colab.research.google.com/github/manikant070/manikant/blob/main/python17_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
d = np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [4]:
np.mean(d)

40.0

In [5]:
np.median(d)

40.0

In [7]:
np.var(d)

400.0

In [8]:
np.min(d)

10

In [9]:
np.max(d)

70

In [11]:
np.quantile(d,0.25)#first np.quantile

30.0

In [12]:
np.quantile(d,0.50)#second np.quantile

40.0

In [13]:
np.quantile(d,0.75)#third np.quantile

50.0

np.random.rand(

In [25]:
r=np.random.rand(5,3)
r

array([[0.01449199, 0.11379012, 0.29604801],
       [0.66341123, 0.55940981, 0.05918693],
       [0.48307221, 0.96162309, 0.32958067],
       [0.71549787, 0.3021165 , 0.49047649],
       [0.7969807 , 0.56954558, 0.72328796]])

In [26]:
r.shape

(5, 3)

In [27]:
r.ndim

2

In [29]:
p=np.random.rand(5,3,2)
p

array([[[0.04591447, 0.18061925],
        [0.35169123, 0.74361366],
        [0.16773932, 0.88570591]],

       [[0.23061242, 0.22060686],
        [0.77981969, 0.79458206],
        [0.50620123, 0.82861214]],

       [[0.9321017 , 0.24522899],
        [0.36810862, 0.30975351],
        [0.82268287, 0.91395297]],

       [[0.16108823, 0.72985019],
        [0.37880916, 0.53663697],
        [0.36836798, 0.17781018]],

       [[0.24779972, 0.9693592 ],
        [0.50221428, 0.64293221],
        [0.66692132, 0.10924631]]])

In [32]:
p.shape


(5, 3, 2)

In [33]:
p.size

30

In [36]:
p.ndim

3

In [39]:
b=np.random.randn(5,3)    #-3 to +3 standard normal data in randn
b

array([[ 0.0345861 ,  0.08756037,  2.95126235],
       [-0.77116641,  0.38570315, -1.58920013],
       [ 0.16016845, -0.37993069, -0.22138164],
       [ 3.45469383, -0.75661   , -0.15260524],
       [-0.27182908,  0.47727711,  0.52525969]])

In [40]:
r

array([[-1.16169093,  1.135307  , -0.08672147],
       [-1.20649918,  0.21775771, -1.11944005],
       [-1.40519669,  0.22914479, -0.22132714],
       [ 1.08984811, -0.80084633, -1.13444736],
       [ 0.35060047, -0.59227869, -1.04988158]])

In [44]:
w=np.random.normal(5,3,(2,3))
w

array([[ 2.37188485,  3.34020794,  7.12546774],
       [ 1.88193168, -1.31296503,  6.43250011]])

In [48]:
np.random.randint(35,86,(5,5))

array([[48, 85, 61, 69, 38],
       [35, 79, 62, 76, 39],
       [72, 75, 66, 47, 50],
       [84, 62, 52, 70, 40],
       [55, 59, 58, 51, 72]])