<a href="https://colab.research.google.com/github/manikant070/manikant/blob/main/python17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# numpay                           array operation
# pandas                           data manipulation and analysis
# matplotlib and seaborn           Graphical analysis
# sklearn                          Machine learning algoritmand technique
# statsmodels                      Statistical analysis
# scipy                            Scientific analysis


In [ ]:
# shape size ndim np.reshape

In [2]:
j = [5,6,8,59,25,3,4,8]
j

[5, 6, 8, 59, 25, 3, 4, 8]

In [5]:
d=np.array(j)
d

array([ 5,  6,  8, 59, 25,  3,  4,  8])

In [4]:
tuple(j)

(5, 6, 8, 59, 25, 3, 4, 8)

In [7]:
d.shape

(8,)

In [8]:
d.ndim

1

In [9]:
d.size

8

In [22]:
h = d.reshape(2,4)
h

array([[ 5,  6,  8, 59],
       [25,  3,  4,  8]])

In [23]:
h.size

8

In [24]:
h.shape

(2, 4)

In [25]:
h.ndim

2

In [34]:
h.reshape()

array([[[ 5,  6],
        [ 8, 59]],

       [[25,  3],
        [ 4,  8]]])

In [13]:
s = [[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [14]:
type(s)

list

In [16]:
m = np.array(s)
m

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [17]:
m.shape

(5, 4)

In [18]:
m.size

20

In [19]:
m.ndim

2

In [36]:
m

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [38]:
q=m.reshape(2,2,5)
q

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [39]:
q.shape

(2, 2, 5)

In [40]:
q.ndim

3

In [46]:
y = m.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [47]:
y.shape

(20,)

In [48]:
y.size

20

In [49]:
y.ndim

1

In [50]:
z = m.reshape(20,1)
z

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [67],
       [89],
       [50],
       [49],
       [77],
       [88],
       [22],
       [55],
       [90],
       [40],
       [70],
       [60]])

In [51]:
z.ndim

2

In [56]:
g=z.reshape(2,2,5,1)
g

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [57]:
g.ndim

4

In [60]:
for i in range(3,101,2):
  print(i)

3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [64]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [65]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [67]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [72]:
j = [5,8,7,23,46,62,84,45,77,33,80]
j

[5, 8, 7, 23, 46, 62, 84, 45, 77, 33, 80]

In [87]:
y=[]
x=[]
for i in range(len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])