<a href="https://colab.research.google.com/github/manikant070/manikant/blob/main/python20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
b=np.random.randint(20,80,(5,5))
b

array([[22, 61, 70, 64, 71],
       [32, 38, 42, 74, 73],
       [38, 77, 65, 25, 58],
       [32, 70, 30, 41, 23],
       [58, 30, 74, 54, 54]])

In [6]:
b[0,1]

61

In [7]:
b[4,3]

54

In [13]:
b[2:4,1:4]

array([[77, 65, 25],
       [70, 30, 41]])

In [14]:
d = np.random.randint(20,80,(8,9))
d

array([[49, 28, 79, 22, 20, 70, 54, 23, 54],
       [32, 57, 75, 77, 30, 56, 55, 78, 32],
       [66, 25, 74, 26, 79, 56, 78, 22, 35],
       [58, 58, 21, 59, 34, 26, 47, 45, 32],
       [60, 72, 27, 44, 69, 43, 49, 63, 66],
       [55, 35, 56, 47, 45, 71, 78, 50, 50],
       [54, 45, 79, 47, 42, 74, 63, 36, 61],
       [62, 29, 55, 35, 76, 20, 39, 35, 53]])

In [15]:
d[0,1]

28

In [19]:
d[2:7]

array([[66, 25, 74, 26, 79, 56, 78, 22, 35],
       [58, 58, 21, 59, 34, 26, 47, 45, 32],
       [60, 72, 27, 44, 69, 43, 49, 63, 66],
       [55, 35, 56, 47, 45, 71, 78, 50, 50],
       [54, 45, 79, 47, 42, 74, 63, 36, 61]])

In [20]:
d[1:5,1:6]

array([[57, 75, 77, 30, 56],
       [25, 74, 26, 79, 56],
       [58, 21, 59, 34, 26],
       [72, 27, 44, 69, 43]])

In [21]:
d

array([[49, 28, 79, 22, 20, 70, 54, 23, 54],
       [32, 57, 75, 77, 30, 56, 55, 78, 32],
       [66, 25, 74, 26, 79, 56, 78, 22, 35],
       [58, 58, 21, 59, 34, 26, 47, 45, 32],
       [60, 72, 27, 44, 69, 43, 49, 63, 66],
       [55, 35, 56, 47, 45, 71, 78, 50, 50],
       [54, 45, 79, 47, 42, 74, 63, 36, 61],
       [62, 29, 55, 35, 76, 20, 39, 35, 53]])

array[row_start : row_end : row_step , col_start : col_end : col_step]

pandas

In [22]:
import pandas as pd

In [26]:
k = [[8,5],[6,9],[20,45],[36,45]]
k

[[8, 5], [6, 9], [20, 45], [36, 45]]

In [27]:
np.array(k)

array([[ 8,  5],
       [ 6,  9],
       [20, 45],
       [36, 45]])

In [28]:
pd.Series(k)

0      [8, 5]
1      [6, 9]
2    [20, 45]
3    [36, 45]
dtype: object

In [32]:
pd.DataFrame(k,columns=["A","B"],index=[289,290,291,292])

A   B
289   8   5
290   6   9
291  20  45
292  36  45

In [ ]:
df["A"]

In [36]:
l = np.random.randint(1,100,(9,9))
l

array([[80,  9,  4, 52, 58, 16, 55, 96, 44],
       [89, 89, 54, 36, 53, 47,  4, 20, 17],
       [56, 89, 69, 52, 96, 84, 68, 65, 77],
       [72, 43, 40, 75, 15, 60, 28,  8, 20],
       [79, 35, 99, 68, 96, 46,  7,  4, 96],
       [69, 42,  9, 10, 71, 53, 85, 41, 56],
       [15, 19, 10, 23, 10,  1, 17, 50, 98],
       [56,  2, 80, 63, 90, 72, 70, 73, 93],
       [ 7, 26, 82, 15, 18, 89, 70, 41, 74]])

In [37]:
l[0]

array([80,  9,  4, 52, 58, 16, 55, 96, 44])

In [38]:
l[0,6]

55

In [39]:
l[2:9,1:6]

array([[89, 69, 52, 96, 84],
       [43, 40, 75, 15, 60],
       [35, 99, 68, 96, 46],
       [42,  9, 10, 71, 53],
       [19, 10, 23, 10,  1],
       [ 2, 80, 63, 90, 72],
       [26, 82, 15, 18, 89]])

In [40]:
g = [[54,6],[8,92],[4,5],[3,875],[25,48],[68,98]]
g

[[54, 6], [8, 92], [4, 5], [3, 875], [25, 48], [68, 98]]

In [41]:
pd.series(g)

AttributeError: module 'pandas' has no attribute 'series'

In [43]:
pd.DataFrame(g,columns=["sub","marks"],index=[1,2,3,4,5,6])

sub  marks
1   54      6
2    8     92
3    4      5
4    3    875
5   25     48
6   68     98

In [44]:
df["sub"]

SyntaxError: invalid syntax (<ipython-input-44-419fda1915a4>, line 1)